### ISSUE TITLE
Invalid RDF/XML output

### ISSUE THREAD

**Issue by GitHubber1** [marcelotto/spread2rdf#6]
Hello Marcel,

I am trying to use your tool for transforming excel-based data to RDF/XML. The problem is that the output XML is not valid because of missing XML end tags. This is the case for property elements on a node element, e.g. skos:broader and skos:InScheme tags are not closed in the following snippet:

```
<skos:Concept rdf:about='http://www.example.com#Whatever'>
    <rdf:type rdf:resource='http://www.example.com#MyType'></rdf:type>
    <myprop:example>value</myprop:example>
    <skos:broader rdf:resource='http://www.example.com#Broader'>
    <skos:inScheme rdf:resource='http://www.example.com#inScheme'>
  </skos:Concept>
```

Using any other format (nt, n3, ttl, xml (TriX), json) validation is successful and I can add and query the data in a triple store.

Does anybody else have this problem?

Thank you,
Andy

**Comment by marcelotto** [comment]
Hi Andy,

since the other formats are generated correctly, it might be a problem in [RDF.rb](https://github.com/ruby-rdf/rdf)'s RDF/XML writer. To ensure it's not a problem with Spread2RDF, please try to convert one of the valid output files to RDF/XML with the following command:

```
$ rdf serialize your-file.ttl --output-format rdfxml -o your-file.rdf
```

If the RDF/XML produced with this command-line interface of RDF.rb is still invalid, I would encourage you to raise an [issue on the RDF/XML writer](https://github.com/ruby-rdf/rdf-rdfxml/issues). Otherwise I can't provide any further help without the input data and the mapping file.

Cheers, 
Marcel

**Comment by GitHubber1** [comment]
Hello Marcel,
thank you very much for your fast help. Converting the .ttl file with the command line also results in an invalid RDF/XML file. I raised an issue [here](https://github.com/ruby-rdf/rdf-rdfxml/issues/28).
Best regards,
Andy

**Comment by marcelotto** [comment]
To check wether the problem is caused by Spread2RDF and work on it, I must reproduce the problem. Can you provide the mapping and, if your data is sensitive, some dummy data exhibiting the problem, possibly by personal mail?
